name: profile_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  dio: ^4.0.6
  shared_preferences: ^2.0.17
  freezed_annotation: any

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.16.4
  mocktail: ^0.3.0
  build_runner: any
  freezed: any
  json_serializable: any
